### ISSUE TITLE
Center icon with button 

### ISSUE THREAD

**Issue by TdfGomes** [pedrocostadev/react-carousel-query#1]
Hi there!
Maybe is my eyes or my monitor but for me it seems the icon is slightly offset 
![Screenshot 2021-02-02 at 17 17 59](https://user-images.githubusercontent.com/9661056/106637585-cd513980-657a-11eb-9b91-63c82939964c.png)
So to start I would like to contribute for this awesome project with a fix for this issue if you agree.

Wish all the best for this!!

**Comment by pedrocostadev** [comment]
Hey, thanks for reporting this issue.
Let me check the PR :-)
