### ISSUE TITLE
Add eslint and prettier

### ISSUE THREAD

**Issue by TdfGomes** [pedrocostadev/react-carousel-query#7]
I think it's a huge benefit having a code rules and style as standard as possible.
Have linting is a way to test our code in the fly and warn us that we are doing something wrong, and also have the same configuration to all contributors.

**Comment by pedrocostadev** [comment]
We already have lint and prettier but will be good to add new rules like `react-hooks`.

**Comment by TdfGomes** [comment]
Doing that!
